---
title: "Capstone"
author: "Praneeth, Marcie, Scott, Sara"
date: "Oct 03, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Input Data
```{r}
source("functions_and_data.R")

calls <- readRDS("data/rdas/calls.rda")
```

## Install Libraries
```{r}
library(dplyr)
library(tidyverse)
library(lubridate)
library(prophet)
library(data.table)
library(ggplot2)
library(forecast)
library(DataCombine)
library(Metrics)
library(timeDate)
library(MLmetrics)
```

## Data Prep (Create Test, Train datasets)
```{r}
calls$call_typ_cd <- factor(calls$call_typ_cd)
summary(calls)
calls_noint <- subset(calls, call_typ_cd != 'Internal')
summary(calls_noint)

calls2014 <- subset(calls, call_start_dttm <= as.POSIXct('2014-12-31 23:00'))
calls2015 <- subset(calls, call_start_dttm >= as.POSIXct('2014-12-31 23:00'))

Date <- format(as.POSIXct(strptime(calls2014$call_start_dttm,"%Y-%m-%d %H:%M:%S",tz="")) ,format = "%Y-%m-%d")
calls2014$date <- Date
Date<- format(as.POSIXct(strptime(calls2015$call_start_dttm,"%Y-%m-%d %H:%M:%S",tz="")) ,format = "%Y-%m-%d")
calls2015$date <- Date

call_day_2014 <- calls2014 %>%
  group_by(date) %>%
  summarise(y = n())

call_day_2014<- call_day_2014[1:365,]

call_day_2015full <- calls2015 %>%
  group_by(date) %>%
  summarise(y = n())

# Couldn't sort as date is chr, so split the data, add and combine later
# call_day_2015[with(call_day_2015, order(date)),]

# split data
call_day_2015sub1 <- call_day_2015full[1:196,]
call_day_2015sub2 <- call_day_2015full[197:363,]

#missing data replaced with previous years day of week calls
newrow1<-data.frame(date='2015-07-16', y= (filter(call_day_2014, date == "2014-07-17")$y))
newrow2<-data.frame(date='2015-07-17', y= (filter(call_day_2014, date == "2014-07-18")$y))

call_day_2015 <- rbind(call_day_2015sub1,newrow1)
call_day_2015 <- rbind(call_day_2015,newrow2)
call_day_2015 <- rbind(call_day_2015,call_day_2015sub2)

callsbyday <- rbind(call_day_2014,call_day_2015)
```

## Lagged Naive Models
```{r}
#Created lags
library(DataCombine)
callsbyday$date<-as.Date(callsbyday$date,"%Y-%m-%d")
laggedcalls<-as.data.frame(callsbyday)
laggedcalls <- slide(laggedcalls, "y", NewVar = "ylag1", slideBy = -1)
laggedcalls <- slide(laggedcalls, "y", NewVar = "ylagyear", slideBy = -364)

#Extracted 2015
lagged2015<-subset(laggedcalls, date>=as.POSIXct('2015-01-01'))

#Errors for both models
lagged2015$lag1error<-lagged2015$y-lagged2015$ylag1
lagged2015$lagyearerror<-lagged2015$y-lagged2015$ylagyear

#RMSE for both models
lag1RMSE<-sqrt(mean(lagged2015$lag1error^2))
lagyearRMSE<-sqrt(mean(lagged2015$lagyearerror^2))

#Percent Error
lagged2015$lag1pcterror<-lagged2015$lag1error/lagged2015$y
lagged2015$lagyearpcterror<-lagged2015$lagyearerror/lagged2015$y

#MAPE
lag1MAPE<-mean(abs(lagged2015$lag1pcterror))
lagyearMAPE<-mean(abs(lagged2015$lagyearpcterror))

#Prediction
lagged2015$month<-months(as.Date(lagged2015$date))

lagged2015_december<-lagged2015%>%
 filter(month=="December")%>%
 select(date, y, ylagyear)
```

## Plots for naive model
```{r}
#Plotting 1-day Lagged Forecast
ggplot(lagged2015, aes(date, y))+
 geom_line()+
 geom_line(aes(y=ylag1), color= "red")+
 ggtitle("1-Day Lagged Naive Model")+
 xlab("Date")+
 ylab("Number of Calls")+
 theme_minimal()+
 theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

#Plotting 1-Year Lagged Forecast
ggplot(lagged2015, aes(date, y))+
 geom_line()+
 geom_line(aes(y=ylagyear), color= "blue")+
 ggtitle("1-Year Lagged Naive Model")+
 xlab("Date")+
 ylab("Number of Calls")+
 theme_minimal()+
 theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
 
 #December Predictions
ggplot(lagged2015_december, aes(date, ylagyear))+
 geom_line(color="blue")+
 geom_line(aes(date, y))+
 ggtitle("Predicted calls in December 2015 Using 1-Year Lagged Model")+
 xlab("Date")+
 ylab("Number of Calls")+
 theme_minimal()+
 theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```

## Build Auto-ARIMA model
```{r}
arima2014 <- call_day_2014[,2]
arimadata2014 <- ts(arima2014)

fit <- auto.arima(arimadata2014, seasonal = TRUE)
summary(fit) #Train MAE = 1942

xyz<-predict(fit, 365)
call_day_2015$predict <- xyz$pred

round(RMSE(call_day_2015$y, call_day_2015$predict))
MAE(call_day_2015$y, call_day_2015$predict)
round(MAPE(call_day_2015$y, call_day_2015$predict), 2)

```

# Prophet model
```{r}
ts_calls <- callsbyday

colnames(ts_calls)[colnames(ts_calls) == 'date'] <- 'ds'
ts_calls$ds <-as_date(ts_calls$ds)
summary(ts_calls$ds)

call2014 <- subset(ts_calls, ds <= as.POSIXct('2014-12-31'))
call2015 <- subset(ts_calls, ds > as.POSIXct('2014-12-31 '))

USholiday <- data_frame(
 holiday = 'USholiday',
 ds = as.Date(c("2014-01-01", "2014-01-20","2014-02-14", "2014-02-17",
                "2014-05-26", "2014-07-04", "2014-09-01", "2014-10-13",
                "2014-11-11", "2014-11-27", "2014-12-25", "2015-01-01",
                "2015-01-19", "2015-02-14", "2015-02-16", "2015-05-25",
                "2015-07-03", "2015-09-07", "2015-10-12", "2015-11-11",
                "2015-11-26", "2015-12-25")),
 lower_window = 0,
 upper_window = 1
)

#Use one year data
m <- prophet(holidays = USholiday,
            seasonality.mode = 'multiplicative',
            changepoint.prior.scale = 0.05)
m <- add_seasonality(m, 'yearly', period = 365, fourier.order = 8, mode = 'multiplicative')

m <- fit.prophet(m, call2014)
future <- make_future_dataframe(m, periods = 365)
forecast1 <- predict(m, future)
tail(forecast1[c('ds', 'yhat', 'yhat_lower', 'yhat_upper')])
plot(m, forecast1) + add_changepoints_to_plot(m)
prophet_plot_components(m, forecast1)
df.cv <- cross_validation(m, initial = 180, period = 45, horizon = 30, units = 'days')
head(df.cv)
df.p <- performance_metrics(df.cv)
head(df.p)
plot_cross_validation_metric(df.cv, metric = 'mape')

#RMSE FOR THE TS2014(TRAINING DATA)
forecast1$ds <-as_date(forecast1$ds)
tsprediction1 <- merge(x=forecast1,y=call2014,by="ds")

RMSE(tsprediction1$yhat,tsprediction1$y)
MAE(tsprediction1$yhat,tsprediction1$y)

#RMSE FOR THE TS2015(TESTING DATA)
forecast1$ds <-as_date(forecast1$ds)
tsprediction1 <- merge(x=forecast1,y=call2015,by="ds")

round(RMSE(tsprediction1$yhat,tsprediction1$y))
MAE(tsprediction1$yhat,tsprediction1$y)
round(MAPE(tsprediction1$yhat,tsprediction1$y),2)

```

# EDA/Visualizations - Calls
```{r}
# Calls by day of week
callsbyday$dayofweek <- weekdays(as.Date(callsbyday$date))
callsbyday$dayofweek <- factor(callsbyday$dayofweek)
callsbyday$month <- months(as.Date(callsbyday$date))

ggplot(callsbyday, aes(x=dayofweek, y=y)) +
  stat_summary(fun.y="mean", geom="bar")

# Average calls per day of week (***need to order by day of week)
ggplot(callsbyday, aes(x=factor(dayofweek), y=y)) +
  stat_summary(fun.y="mean", geom="bar") +
  ggtitle("Avg. Calls per Day by Day of Week")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  xlab("Day of Week") +
  ylab("Number of Calls per Day")

# Average calls per day in month (***need to order by month)
ggplot(callsbyday, aes(x=factor(month), y=y)) +
  stat_summary(fun.y="mean", geom="bar") +
  ggtitle("Avg. Calls per day by Month") +
  labs(y="Number of Calls per day", x = "Month") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"))

```

# EDA/Visualizations - Call duration
```{r}
call_assoc <- readRDS("data/rdas/call_assoc.rda")

#with assoc_party_id in each call_id
call_dur <- left_join(calls, call_assoc, by = "call_id")

Date <- format(as.POSIXct(strptime(call_dur$call_start_dttm,"%Y-%m-%d %H:%M:%S",tz="")) ,format = "%Y-%m-%d")
Month <- format(as.POSIXct(strptime(call_dur$call_start_dttm,"%Y-%m-%d %H:%M:%S",tz="")) ,format = "%Y-%m")
Month <- format(as.POSIXct(strptime(Month,"%Y-%m",tz="")) ,format = "%Y-%m-%d")

call_dur$date <- Date
call_dur$month <- Month
summary(call_dur)

#Avg. call_duration time by day, month, workgroup and associate party
call_dur_day <- call_dur %>%
  group_by(date) %>%
  summarise_at(vars(assoc_durtn_tm), funs(mean(., na.rm=TRUE)))

call_dur_asso <- call_dur %>%
  group_by(assoc_party_id) %>%
  summarise_at(vars(assoc_durtn_tm), funs(mean(., na.rm=TRUE)))

call_dur_month <- call_dur %>%
  group_by(month) %>%
  summarise_at(vars(assoc_durtn_tm), funs(mean(., na.rm=TRUE)))

# Call duration by work groups
call_dur_workgroup <- call_dur %>%
  group_by(wrk_grp_id) %>%
  summarise_at(vars(assoc_durtn_tm), funs(mean(., na.rm=TRUE)))
  
# Add date Indicators
call_dur_day$dayofweek <- weekdays(as.Date(call_dur_day$date))
call_dur_day$month <- months(as.Date(call_dur_day$date))
call_dur_day$date <-as.Date(call_dur_day$date)

holiday1415 <- as.Date(c("2014-01-01", "2014-01-20","2014-02-14", "2014-02-17", "2014-05-26", "2014-07-04", "2014-09-01", "2014-10-13", "2014-11-11", "2014-11-27", "2014-12-25", "2015-01-01", "2015-01-19", "2015-02-14", "2015-02-16", "2015-05-25", "2015-07-03", "2015-09-07", "2015-10-12", "2015-11-11", "2015-11-26", "2015-12-25"))
call_dur_day$holiday <- ifelse(call_dur_day$date %in% holiday1415, 1, 0)
str(call_dur_day)

# Call duration by Month
call_dur_day$month <- factor(call_dur_day$month, levels = c('January','February','March','April','May','June','July','August','September','October','November','December'))
ggplot(call_dur_day, aes(x=month, y=assoc_durtn_tm)) +
  stat_summary(fun.y="mean", geom="bar") +
  ggtitle("Avg. call duration per day by Month") +
  labs(y="Call duration per day", x = "Month") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"))

ggplot(call_dur_day, aes(x=factor(holiday), y=assoc_durtn_tm)) +
  stat_summary(fun.y="mean", geom="bar") +
  ggtitle("Avg. call duration per day by Holidays/Not") +
  labs(y="Call duration per day", x = "Holiday Indicator")

# Call duration by work group names
wrk_grp <- readRDS("data/rdas/wrk_grp.rda")

call_dur_wrkgrp <- left_join(call_dur_workgroup, wrk_grp, by = "wrk_grp_id")

# Call duration by work group
ggplot(call_dur_wrkgrp, aes(x=factor(wrk_grp_desc), y=assoc_durtn_tm)) +
  stat_summary(fun.y="mean", geom="bar") +
  ggtitle("Avg. call duration per day by Work Group") +
  labs(y="Call duration per day", x = "Work Group") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"))

```
 
## Code from Daniel
```{r}
calls <- readRDS("data/rdas/calls.rda")

daily_ib_calls <- calls %>% 
  filter(year(call_start_dttm) == 2014) %>% 
  count(dt = floor_date(call_start_dttm, "1 day"))

daily_ib_calls %>% 
  ggplot(aes(dt, n)) +
  geom_line()

daily_ib_calls %>% 
  mutate(weekend_ind = if_else(wday(dt) %in% c(7,1), "Weekend", "Weekday")) %>% 
  ggplot(aes(dt, n, color = weekend_ind)) +
  geom_line()

#Create a dataset of daily calls for 2014 and 2015 and align on day of week
yoy <- calls %>% 
  transmute(yr = year(call_start_dttm),
            dt = floor_date(call_start_dttm, "1 day"),
            dt = if_else(yr == 2014, dt + years(1) - days(1), dt) %>% ymd
  ) %>% 
  count(yr, dt) %>% 
  spread(yr, n) %>% 
  mutate(err = `2015` - `2014`,
         abs_err = abs(err),
         abs_perc_err = round(abs_err / `2015`, 3) * 100
  ) %>% 
  select(-`2014`, -`2015`) %>% 
  gather(key, value, -dt)

#Compare ME, MAE, and MAPE
yoy %>% 
  ggplot(aes(dt, value, color = key)) +
  geom_line() +
  facet_grid(key~., scales = "free_y")

#Identify days with abnormally large perc error - holidays?
yoy %>% 
  filter(key == "abs_perc_err") %>% 
  mutate(label = ifelse(value >= 40, dt, NA)) %>% 
  ggplot(aes(dt, 
             value, 
             label = label %>% 
               as.Date(origin = "1970-01-01") %>% 
               format("%b-%d")
  )
  ) +
  geom_line() +
  geom_text(color = "red") +
  coord_cartesian(ylim = c(0,100)) +
  scale_y_continuous(expand = c(0,0),
                     breaks = seq(0, 100, 20),
                     minor_breaks = seq(0, 100, 5)
  )

# If we exclude a few extraordinary days where holidays are misaligned, average error is under 800 calls/day if we only use 2014 inbound call count to predict 2015 call count and nothing else.  Holidays can obviously be adjusted and a trend can be applied.

yoy %>% 
  filter(key == "abs_err") %>% 
  ggplot(aes(dt, 
             value
  )
  ) +
  geom_line() +
  geom_hline(yintercept = yoy %>% 
               filter(key == "abs_err",
                      value < 3000
               ) %>% 
               {mean(.$value)},
             color = "red",
             linetype = "dashed"
  ) +
  scale_y_continuous("Number of Calls (Error)",
                     expand = c(0,0),
                     breaks = seq(0,12000, 1000),
                     minor_breaks = seq(0,12000, 500)
  ) +
  scale_x_date(element_blank(),
               date_minor_breaks = "1 month"
  )
```

## Naive & Mean Model
```{r model building}

#mean model by year - no data split
nrow(calls2014)
# 2582385/365 = 7075.027
nrow(calls2015) #2810484/365 = 7699.956

calls2015num <- calls2015 %>%
 group_by(calls2015$date) %>%
 summarise(y = n())

calls2015num$predicted <- 7075.027 # make new column 
head(calls2015num)

calls2015num$change <- abs(calls2015num$y - calls2015num$predicted)

mean(calls2015num$change) #2726.725 Mean absolute error

#take test and train dataset mean model with data split
set.seed(100)
rows <- createDataPartition(calls2014$call_id, p = .5, list = FALSE)
train <- calls2014[rows, ]
test <- calls2014[-rows, ]

Date<- format(as.POSIXct(strptime(train$call_start_dttm,"%Y-%m-%d %H:%M:%S",tz="")) ,format = "%Y-%m-%d")
train$date <- Date

trainnum <- train %>%
 group_by(train$date) %>%
 summarise(y = n())
#View(trainnum)
mean(trainnum$y)#3527.85 because this figure represents 50% of the data, we take 3527.85/.5 = 7055.70 to approximate the rest of the data. 

#compare 2014 train to test
Date<- format(as.POSIXct(strptime(test$call_start_dttm,"%Y-%m-%d %H:%M:%S",tz="")) ,format = "%Y-%m-%d")
test$date <- Date

testnum <- test %>%
 group_by(test$date) %>%
 summarise(y = n())
testnum$predicted <- 3527.85 # make new column 
head(testnum)
testnum$change <- abs(testnum$y - testnum$predicted)

mean(testnum$change) #1146.314 Mean absolute error times 2 because this is half the data 2292.628

#compare 2014 train to 2015 whole

Date<- format(as.POSIXct(strptime(calls2015$call_start_dttm,"%Y-%m-%d %H:%M:%S",tz="")) ,format = "%Y-%m-%d")
calls2015$date <- Date

calls2015num <- calls2015 %>%
 group_by(calls2015$date) %>%
 summarise(y = n())
calls2015num$predicted <- 7055.70 # make new column 
head(calls2015num)
calls2015num$change <- abs(calls2015num$y - calls2015num$predicted)

mean(calls2015num$change) #2734.126 Mean absolute error

#Mean Model
#Summary of MAE
#no data split 2014 to predict 2015 2726.725
#data split 50/50 of 2014 one half to predict the other half 2292.628
#data split 50/50 on 2014 train to predict 2015 2734.126

```

## Other EDA (Below code works, but call_day doesn't have 730 rows)

```{r}
call_day <- callsbyday

# Calls trend by date
ggplot(call_day, aes(call_day$date,call_day$y))+
  geom_point()

# number of calls per incident
call_incdnt <- readRDS("data/rdas/call_incdnt.rda")

call_incident_combined <-left_join(call_incdnt, calls, by = "call_id")
call_per_incident <- call_incident_combined %>%
  group_by(incdnt_id) %>%
  summarise(number_of_calls = n())
summary(call_per_incident) # Mean = 1.201

# number of incidents per call
incident_per_call <- call_incident_combined %>%
  group_by(call_id) %>%
  summarise(number_of_incident = n())
summary(incident_per_call) # Mean = 1.509

```
